[package]
name = "cargo-flow"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
cargo_metadata = "0.19"
clap = { version = "4.5", features = [ "derive" ] }
serde = { version = "1", features = [ "derive" ] }
serde_yaml = "0.9"
